### ISSUE TITLE
Hi, Sorry for interrupt!

### ISSUE THREAD

**Issue by jasper-oh** [Yogesh-10/dsa-interview-resource#1]
Hello, This is jasper.
First, sorry for messing up your repository with an issue.
I think I encountered the same problem that you posted in the Github community: the contribution year went down to 2009. 
My question is How did you solve it? Is this issue just disappear automatically? or Did you do something in your repository?

Thanks in advance.
Jasper

**Comment by Yogesh-10** [comment]
Hello Jasper. I don't see any issue in your account. But, It did get resolved automatically for me. I just raised a ticket in github support.
